2019-11-27 22:30:09,535 DEBUG   MainThread:51513 [wandb_config.py:_load_defaults():110] no defaults not found in config-defaults.yaml
2019-11-27 22:30:09,540 DEBUG   MainThread:51513 [cmd.py:execute():722] Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=<valid stream>)
2019-11-27 22:30:09,552 DEBUG   MainThread:51513 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:09,562 DEBUG   MainThread:51513 [cmd.py:execute():722] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:09,582 DEBUG   MainThread:51513 [run_manager.py:__init__():535] Initialized sync for reinforce/a9twldj5
2019-11-27 22:30:09,584 INFO    MainThread:51513 [run_manager.py:wrap_existing_process():1131] wrapping existing process 51507
2019-11-27 22:30:09,585 WARNING MainThread:51513 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2019-11-27 22:30:09,604 DEBUG   MainThread:51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2019-11-27 22:30:09,892 DEBUG   MainThread:51513 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 37940
2019-11-27 22:30:09,968 INFO    MainThread:51513 [run_manager.py:init_run():916] system metrics and metadata threads started
2019-11-27 22:30:09,969 INFO    MainThread:51513 [run_manager.py:init_run():950] upserting run before process can begin, waiting at most 10 seconds
2019-11-27 22:30:09,977 DEBUG   Thread-14 :51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-27 22:30:10,338 DEBUG   Thread-14 :51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 555
2019-11-27 22:30:10,344 INFO    Thread-14 :51513 [run_manager.py:_upsert_run():1035] saving patches
2019-11-27 22:30:10,344 DEBUG   Thread-14 :51513 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:10,356 DEBUG   Thread-14 :51513 [cmd.py:execute():722] Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:10,369 DEBUG   Thread-14 :51513 [cmd.py:execute():722] Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:10,383 DEBUG   Thread-14 :51513 [cmd.py:execute():722] Popen(['git', 'version'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:10,417 DEBUG   Thread-14 :51513 [cmd.py:execute():722] Popen(['git', 'merge-base', 'HEAD', 'e6c9af4e7a283fa331653715d8a92df3f996701d'], cwd=/Users/jeongsooha/project/ReinforcementLearning, universal_newlines=False, shell=None, istream=None)
2019-11-27 22:30:10,430 INFO    Thread-14 :51513 [run_manager.py:_upsert_run():1039] saving pip packages
2019-11-27 22:30:10,430 INFO    Thread-14 :51513 [run_manager.py:_upsert_run():1041] initializing streaming files api
2019-11-27 22:30:10,431 INFO    Thread-14 :51513 [run_manager.py:_upsert_run():1048] unblocking file change observer, beginning sync with W&B servers
2019-11-27 22:30:10,431 INFO    MainThread:51513 [run_manager.py:wrap_existing_process():1148] informing user process we are ready to proceed
2019-11-27 22:30:10,434 INFO    MainThread:51513 [run_manager.py:_sync_etc():1255] entering loop for messages from user process
2019-11-27 22:30:10,435 DEBUG   Thread-15 :51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-27 22:30:10,539 INFO    Thread-3  :51513 [run_manager.py:_on_file_modified():682] file/dir modified: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/config.yaml
2019-11-27 22:30:10,545 DEBUG   Thread-3  :51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-27 22:30:10,747 INFO    MainThread:51513 [run_manager.py:_sync_etc():1278] received message from user process: {"exitcode": 0}
2019-11-27 22:30:10,747 INFO    MainThread:51513 [run_manager.py:_sync_etc():1364] closing log streams and sending exitcode to W&B
2019-11-27 22:30:10,747 INFO    MainThread:51513 [run_manager.py:shutdown():1055] shutting down system stats and metadata service
2019-11-27 22:30:10,765 DEBUG   Thread-15 :51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 46
2019-11-27 22:30:10,904 DEBUG   Thread-3  :51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 603
2019-11-27 22:30:10,909 INFO    Thread-3  :51513 [run_manager.py:_on_file_created():671] file/dir created: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/diff.patch
2019-11-27 22:30:10,910 INFO    Thread-3  :51513 [run_manager.py:_on_file_created():671] file/dir created: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/wandb-metadata.json
2019-11-27 22:30:10,910 INFO    Thread-3  :51513 [run_manager.py:_on_file_created():671] file/dir created: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/output.log
2019-11-27 22:30:10,911 INFO    Thread-3  :51513 [run_manager.py:_on_file_created():671] file/dir created: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/requirements.txt
2019-11-27 22:30:10,970 INFO    MainThread:51513 [run_manager.py:shutdown():1067] stopping streaming files and file change observer
2019-11-27 22:30:11,543 INFO    Thread-3  :51513 [run_manager.py:_on_file_modified():682] file/dir modified: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/wandb-metadata.json
2019-11-27 22:30:11,544 INFO    MainThread:51513 [run_manager.py:_on_file_created():671] file/dir created: /Users/jeongsooha/project/ReinforcementLearning/a3c/wandb/run-20191127_133008-a9twldj5/wandb-events.jsonl
2019-11-27 22:30:11,553 DEBUG   MainThread:51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-27 22:30:11,906 DEBUG   MainThread:51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 603
2019-11-27 22:30:12,548 DEBUG   Thread-18 :51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-27 22:30:12,926 DEBUG   Thread-18 :51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 785
2019-11-27 22:30:12,932 DEBUG   Thread-18 :51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-27 22:30:13,464 DEBUG   Thread-18 :51513 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/jeongsoo-ha1210/reinforce/a9twldj5/___batch_archive_1.tgz?Expires=1574861472&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=SD8Xyuct3us%2FUH2ttq7y4Q%2B8bcu%2FdwuJnIotVNsY4dXUqkkm3rR1OG5y208IQ8mxTDMmOtrOIuvuUtDOH3EeO1RDIzHxOKYGJUMEtj4YH7rI%2BBumiCYNfZXZw8IpkouO53rn0%2BNvtA4BrGf7ZX03HibbG2pVVHuaqSVe4gFfzP1a3vrQLyhAVh%2FGG%2FsEV2QhG9AjxVVrntzCl9DXXJ8AQvDP3A9r8P1xoxOcs4u0LCpsdrwtxHcNjq83rzugUUe0EEeb5LZaheAYUSmp4P8XKuEwM3L7cmmbXKM%2F5br3AJpLuFCGO5Fo7uUcSyIZlx9dR4g8zkWFv9C5sUvm1UApQw%3D%3D HTTP/1.1" 200 0
2019-11-27 22:30:13,548 DEBUG   Thread-7  :51513 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-27 22:30:13,900 DEBUG   Thread-7  :51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/jeongsoo-ha1210/reinforce/a9twldj5/file_stream HTTP/1.1" 200 311
2019-11-27 22:30:14,096 DEBUG   Thread-7  :51513 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/jeongsoo-ha1210/reinforce/a9twldj5/file_stream HTTP/1.1" 200 308
2019-11-27 22:30:14,097 INFO    MainThread:51513 [run_manager.py:_sync_etc():1416] syncing files to cloud storage
2019-11-27 22:30:14,608 INFO    MainThread:51513 [run_manager.py:_sync_etc():1431] syncing complete: https://app.wandb.ai/jeongsoo-ha1210/reinforce/runs/a9twldj5
2019-11-27 22:30:14,608 INFO    MainThread:51513 [a9twldj5:run_manager.py:_sync_etc():1431] syncing complete: https://app.wandb.ai/jeongsoo-ha1210/reinforce/runs/a9twldj5
